apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kvz
  name: kvz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kvz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kvz
    spec:
      containers:
      - image: docker.internal.10.42.0.28.nip.io:5000/kvz-api-bank
        name: kvz-api-bank
        resources: {}
        imagePullPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kvz
  name: kvz
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kvz
  type: NodePort
status:
  loadBalancer: {}
